name: Build JARs for Release

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-release:
    name: Build and Release All Modules
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
            submodules: recursive

      - name: Set Up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle Packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Modules
        run: |
          MODULES=("AdvancedChatCore" "AdvancedChatBox" "AdvancedChatFilters" "AdvancedChatHUD" "AdvancedChatLog")
          for module in "${MODULES[@]}"; do
            echo "Building $module..."
            cd "$module"
            chmod +x gradlew
            ./gradlew build
            cd ..
          done

      - name: Collect All JARs
        run: |
            mkdir -p all-jars
            shopt -s extglob
            cp */build/libs/!(*-sources).jar all-jars/
        shell: bash

      - name: Upload All JARs as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "AdvancedChat-Jars"
          path: all-jars
          if-no-files-found: error

      - name: Upload JARs to Release
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: "all-jars/*.jar"
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
